---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flowscape
  namespace: flowscape
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flowscape
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
