---
apiVersion: v1
kind: Service
metadata:
  name: advent-wollbi
  namespace: advent-wollbi
  labels:
    app.kubernetes.io/name: advent-wollbi
spec:
  selector:
    app.kubernetes.io/name: advent-wollbi
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
